### ISSUE TITLE
Sequencer Table for the Monthly Data Entry Form.

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#374]
The AddNew button on this form is not working the way it should because the sequencer table of this form is missing. This is very needed.

**Comment by smachua** [comment]
@mhabimana I have included a dialog to update sequencer table for Monthly Data Entry form under the menu Tools -> Sequencer Configuration. See #378 . I have also attached a script file for creating sequencer table for monthly elements. 

[seq_monthly_element.txt](https://github.com/opencdms/Climsoft/files/2388384/seq_monthly_element.txt)

This work affected other modules such as userAdmin and mainMenu. A new dialog (i.e. frmElementSequencerMonthly) was also created.

**Comment by mhabimana** [comment]
@smachua Thanks and noted.

**Comment by mhabimana** [comment]
@Patowhiz  Can you please point the form Monthly Data to the new monthly sequencer (see: Tool,sequencer configuration,Monthly) instead of seq_year?

**Comment by Patowhiz** [comment]
Yeah. I can do that

**Comment by mhabimana** [comment]
@Patowhiz Great thanks

**Comment by isedwards** [comment]
Can someone send me the latest database creation script to make sure I use the correct one to update the model?

**Comment by smachua** [comment]
@isedwards do you want it without any data in test database or in the way we compile it in the setup?

**Comment by isedwards** [comment]
Thanks Samuel. Either is fine - any data that exists is ignored when creating the model and the database schema is the same for both databases.

**Comment by smachua** [comment]
@isedwards I have attached the empty one since it's smaller but it contains both test and operational database schemas

[mariadb_climsoft_db_v4_empty.txt](https://github.com/opencdms/Climsoft/files/2395983/mariadb_climsoft_db_v4_empty.txt)

**Comment by isedwards** [comment]
@smachua - Are the two database schemas still identical?

In theory, would a user be able to create both databases by using a single script and just changing the `CREATE DATABASE` command at the top to the name of the database that they are creating?

**Comment by isedwards** [comment]
This is great thanks

**Comment by smachua** [comment]
@isedwards operational database only.

[mariadb_climsoft_database_db_v4_operational.txt](https://github.com/opencdms/Climsoft/files/2396230/mariadb_climsoft_database_db_v4_operational.txt)

**Comment by mhabimana** [comment]
@Patowhiz Are you OK now ?

**Comment by Patowhiz** [comment]
@mhabimana I'm still waiting for @isedwards pull request to be merged.

**Comment by isedwards** [comment]
@Patowhiz - there was a problem/typo in the description that I posted on GitHub, but the code is okay: the name of the field in the Entity Framework model is the same as the name of the field in the database.

If you want to check this out and use it before it is merged then it is on the branch `Update_EntityModel`.  The branch is identical to master, but with one extra commit, so if you use this branch and create your changes on top of it there won't be any problems when you do a pull request/merge later.

**Comment by Patowhiz** [comment]
@smachua Can you share the filled one. The one that has the key entries that make climsoft testable

**Comment by mhabimana** [comment]
@Patowhiz @smachua - There is still a problem of sequencing on the form Monthly; it is not sequencing automatically to the following year but rather stopping on the next element. If for example one element is set in the sequencer(e.g: element 208),logically,after entering for example monthly data for the year 2000 and save,the **AddNew** should call a blank form with the following year 2001 and so on and so on.

**Comment by mhabimana** [comment]
@Patowhiz : This is happening on the form Monthly only,other forms are working well.

**Comment by mhabimana** [comment]
@Patowhiz - This form is also accepting data for future date,which is not good.

**Comment by mhabimana** [comment]
@Patowhiz - I am happy with the sequencer and future dates behaviour,however,I am getting this error when Uploading;
![image](https://user-images.githubusercontent.com/10340170/86217199-ccd96600-bb87-11ea-9eb6-60fc10f3e69a.png)

**Comment by Patowhiz** [comment]
Thanks @mhabimana . I have fixed that bug.

**Comment by mhabimana** [comment]
@Patowhiz -Thanks,this is now working well and the issue can be closed.

**Comment by mhabimana** [comment]
@Patowhiz - I reopen this because,we are still missing the period of data in the database. Monthly data is a cumulative or average of  the whole month and it was agreed that the period should be the last date to differentiate such data with the rest in the database (e.g.:Hourly,Daily,etc). I think when keying in data in the form,the system should check the year and the month and fill the period box automatically. For example: year 2020 (the period for January should be 31,Feb should be 29,etc).

**Comment by Patowhiz** [comment]
@mhabimana thanks. I have fixed that feature
